version 19
set more off

* Ensure project globals are loaded from standard launcher.
if "$project_root" == "" {
    do "00_global_paths.do"
}

* Prepared data location generated by 01_dataprep_master.do.
global CTData "$Data_share/Output"

global ManuscriptTables "$OutTables/manuscript"
global ManuscriptFigures "$OutFigures/manuscript"
capture mkdir "$ManuscriptTables"
capture mkdir "$ManuscriptFigures"

* 1) Freeze replication conventions.
clear
input str40 key str220 value
"trial_id" "NCT06648226"
"arm_code_1" "control"
"arm_code_2" "health swaps"
"arm_code_3" "climate swaps"
"arm_code_4" "climate + health swaps"
"baseline_visit" "1"
"intervention_visits" "2,3"
"purchase_visit_variable" "visit_store"
"psych_visit_variable" "visit"
"acceptability_visit" "visit 3 only"
"cohen_d_denominator" "Manually entered from Campbell Collaboration mixed-effects calculator; see 03_main_analysis.do comment"
"consort_combined_dropout_rule" "Report CONSORT value=14; keep count_visit diagnostic=34"
"note_not_sure_recode" "notice_* ==2 treated as 0 in rnotice_*"
end

* 2) Participant flow.
use "$CTData/dataset A_nutri and carbon.dta", clear

count if treatment_svy==1 & visit_store==1
local alloc_control = r(N)
count if treatment_svy==3 & visit_store==1
local alloc_climate = r(N)
count if treatment_svy==2 & visit_store==1
local alloc_health = r(N)
count if treatment_svy==4 & visit_store==1
local alloc_combined = r(N)

count if treatment_svy==1 & visit_store==2
local recv2_control = r(N)
count if treatment_svy==3 & visit_store==2
local recv2_climate = r(N)
count if treatment_svy==2 & visit_store==2
local recv2_health = r(N)
count if treatment_svy==4 & visit_store==2
local recv2_combined = r(N)

count if treatment_svy==1 & visit_store==3
local recv3_control = r(N)
count if treatment_svy==3 & visit_store==3
local recv3_climate = r(N)
count if treatment_svy==2 & visit_store==3
local recv3_health = r(N)
count if treatment_svy==4 & visit_store==3
local recv3_combined = r(N)

capture drop count_visit
bysort pid: egen count_visit = count(visit_store)

count if visit_store==1 & count_visit==1 & treatment_svy==1
local noint_control = r(N)
count if visit_store==1 & count_visit==1 & treatment_svy==3
local noint_climate = r(N)
count if visit_store==1 & count_visit==1 & treatment_svy==2
local noint_health = r(N)
count if visit_store==1 & count_visit==1 & treatment_svy==4
local noint_combined = r(N)

tempfile pf
tempname ppf
postfile `ppf' str70 stage int overall int control int climate int health int combined str20 source using `pf', replace
post `ppf' ("Assessed for eligibility")                  (1472) (.)   (.)   (.)   (.)   ("consort_reported")
post `ppf' ("Excluded total")                            (271)  (.)   (.)   (.)   (.)   ("consort_reported")
post `ppf' ("Excluded: did not meet inclusion criteria") (100)  (.)   (.)   (.)   (.)   ("consort_reported")
post `ppf' ("Excluded: duplicate record retained first") (101)  (.)   (.)   (.)   (.)   ("consort_reported")
post `ppf' ("Excluded: dropped before randomization")    (70)   (.)   (.)   (.)   (.)   ("consort_reported")
post `ppf' ("Randomized")                                (1201) (.)   (.)   (.)   (.)   ("consort_reported")
post `ppf' ("Allocated to intervention (visit 1)")       (1201) (`alloc_control') (`alloc_climate') (`alloc_health') (`alloc_combined') ("computed")
post `ppf' ("Received allocated intervention (visit 2)") (.)    (`recv2_control') (`recv2_climate') (`recv2_health') (`recv2_combined') ("computed")
post `ppf' ("Received allocated intervention (visit 3)") (.)    (`recv3_control') (`recv3_climate') (`recv3_health') (`recv3_combined') ("computed")
post `ppf' ("Dropped before receiving intervention")     (.)    (21) (17) (21) (14) ("consort_reported")
post `ppf' ("Dropped before intervention (count_visit diagnostic)") (.) (`noint_control') (`noint_climate') (`noint_health') (`noint_combined') ("computed_diagnostic")
post `ppf' ("Analyzed")                                  (1201) (`alloc_control') (`alloc_climate') (`alloc_health') (`alloc_combined') ("computed")
postclose `ppf'
use `pf', clear

* 3) Baseline (Table 1).
use "$CTData/dataset D_Visit1 demog polsup.dta", clear
capture confirm variable inccat
if _rc gen inccat = income4cat

tempfile baseline
tempname pbl
postfile `pbl' str28 characteristic str52 level ///
    int overall_n double overall_pct ///
    int control_n double control_pct ///
    int climate_n double climate_pct ///
    int health_n double health_pct ///
    int combined_n double combined_pct using `baseline', replace

local vlist "agecat gendercat latino racecat educcat inccat hhcat"
foreach v of local vlist {
    count if `v'!=.
    local den_all_`v' = r(N)
    foreach a in 1 3 2 4 {
        count if `v'!=. & treatment_svy==`a'
        local den_`v'_`a' = r(N)
    }
}

foreach lvl in 1 2 3 4 {
    count if agecat==`lvl'
    local n_all=r(N)
    local p_all=100*`n_all'/`den_all_agecat'
    foreach a in 1 3 2 4 {
        count if agecat==`lvl' & treatment_svy==`a'
        local n_`a'=r(N)
        local p_`a'=100*`n_`a''/`den_agecat_`a''
    }
    local lbl = cond(`lvl'==1,"18-25 years",cond(`lvl'==2,"26-39 years",cond(`lvl'==3,"40-59 years","60 years or older")))
    post `pbl' ("Age") ("`lbl'") (`n_all') (`p_all') (`n_1') (`p_1') (`n_3') (`p_3') (`n_2') (`p_2') (`n_4') (`p_4')
}

foreach lvl in 1 2 3 {
    count if gendercat==`lvl'
    local n_all=r(N)
    local p_all=100*`n_all'/`den_all_gendercat'
    foreach a in 1 3 2 4 {
        count if gendercat==`lvl' & treatment_svy==`a'
        local n_`a'=r(N)
        local p_`a'=100*`n_`a''/`den_gendercat_`a''
    }
    local lbl = cond(`lvl'==1,"Woman",cond(`lvl'==2,"Man","Non-binary or another gender"))
    post `pbl' ("Gender") ("`lbl'") (`n_all') (`p_all') (`n_1') (`p_1') (`n_3') (`p_3') (`n_2') (`p_2') (`n_4') (`p_4')
}

count if latino==1
local n_all=r(N)
local p_all=100*`n_all'/`den_all_latino'
foreach a in 1 3 2 4 {
    count if latino==1 & treatment_svy==`a'
    local n_`a'=r(N)
    local p_`a'=100*`n_`a''/`den_latino_`a''
}
post `pbl' ("Latino") ("Latino(a) or Hispanic ethnicity") (`n_all') (`p_all') (`n_1') (`p_1') (`n_3') (`p_3') (`n_2') (`p_2') (`n_4') (`p_4')

foreach lvl in 1 2 3 5 6 {
    count if racecat==`lvl'
    local n_all=r(N)
    local p_all=100*`n_all'/`den_all_racecat'
    foreach a in 1 3 2 4 {
        count if racecat==`lvl' & treatment_svy==`a'
        local n_`a'=r(N)
        local p_`a'=100*`n_`a''/`den_racecat_`a''
    }
    local lbl = cond(`lvl'==1,"American Indian or Alaska Native",cond(`lvl'==2,"Asian, Native Hawaiian, or another Pacific Islander",cond(`lvl'==3,"Black or African American",cond(`lvl'==5,"White","Another race or multi-racial"))))
    post `pbl' ("Race") ("`lbl'") (`n_all') (`p_all') (`n_1') (`p_1') (`n_3') (`p_3') (`n_2') (`p_2') (`n_4') (`p_4')
}

foreach lvl in 1 3 5 6 {
    count if educcat==`lvl'
    local n_all=r(N)
    local p_all=100*`n_all'/`den_all_educcat'
    foreach a in 1 3 2 4 {
        count if educcat==`lvl' & treatment_svy==`a'
        local n_`a'=r(N)
        local p_`a'=100*`n_`a''/`den_educcat_`a''
    }
    local lbl = cond(`lvl'==1,"High school diploma or less",cond(`lvl'==3,"Some college or associate's degree",cond(`lvl'==5,"College degree","Graduate degree")))
    post `pbl' ("Education") ("`lbl'") (`n_all') (`p_all') (`n_1') (`p_1') (`n_3') (`p_3') (`n_2') (`p_2') (`n_4') (`p_4')
}

foreach lvl in 1 6 8 9 {
    count if inccat==`lvl'
    local n_all=r(N)
    local p_all=100*`n_all'/`den_all_inccat'
    foreach a in 1 3 2 4 {
        count if inccat==`lvl' & treatment_svy==`a'
        local n_`a'=r(N)
        local p_`a'=100*`n_`a''/`den_inccat_`a''
    }
    local lbl = cond(`lvl'==1,"$0 to $49,999",cond(`lvl'==6,"$50,000 to $99,999",cond(`lvl'==8,"$100,000 to $149,999","$150,000 or more")))
    post `pbl' ("Household income, annual") ("`lbl'") (`n_all') (`p_all') (`n_1') (`p_1') (`n_3') (`p_3') (`n_2') (`p_2') (`n_4') (`p_4')
}

foreach lvl in 1 3 5 {
    count if hhcat==`lvl'
    local n_all=r(N)
    local p_all=100*`n_all'/`den_all_hhcat'
    foreach a in 1 3 2 4 {
        count if hhcat==`lvl' & treatment_svy==`a'
        local n_`a'=r(N)
        local p_`a'=100*`n_`a''/`den_hhcat_`a''
    }
    local lbl = cond(`lvl'==1,"1-2",cond(`lvl'==3,"3-4","5 or more"))
    post `pbl' ("Household size") ("`lbl'") (`n_all') (`p_all') (`n_1') (`p_1') (`n_3') (`p_3') (`n_2') (`p_2') (`n_4') (`p_4')
}
postclose `pbl'
use `baseline', clear

* Table 1 display formatting.
gen rowid = _n
foreach arm in overall control climate health combined {
    gen str8 pctdisp_`arm' = cond(missing(`arm'_pct), "", ///
        cond(`arm'_pct<1 & `arm'_pct>0, string(round(`arm'_pct,0.1),"%4.1f") + "%", ///
        string(round(`arm'_pct,1),"%4.0f") + "%"))
    gen str20 celldisp_`arm' = trim(string(`arm'_n,"%12.0gc")) + " (" + pctdisp_`arm' + ")"
}

tempfile table1_display
tempname ptd
postfile `ptd' int row_order byte is_heading str80 label ///
    str20 overall str20 control str20 climate str20 health str20 combined using `table1_display', replace

local row_order = 0
foreach ch in "Age" "Gender" "Latino" "Race" "Education" "Household income, annual" "Household size" {
    if "`ch'" != "Latino" {
        local ++row_order
        post `ptd' (`row_order') (1) ("`ch'") ("") ("") ("") ("") ("")
    }
    preserve
    keep if characteristic=="`ch'"
    sort rowid
    forvalues i=1/`=_N' {
        local lbl = level[`i']
        if "`ch'" != "Latino" local lbl = "    `lbl'"
        local ++row_order
        post `ptd' (`row_order') (0) ("`lbl'") ///
            (celldisp_overall[`i']) (celldisp_control[`i']) (celldisp_climate[`i']) ///
            (celldisp_health[`i']) (celldisp_combined[`i'])
    }
    restore
}
postclose `ptd'

use `table1_display', clear
putexcel set "$ManuscriptTables/table1_participant_characteristics.xlsx", replace
putexcel A1=("Table 1. Participant characteristics, n=1,201 US adults"), bold
putexcel B2:F2=("Participants, N (%)"), merge hcenter bold
putexcel A3=("Characteristic"), bold
putexcel B3=("Overall"), bold hcenter
putexcel C3=("Control"), bold hcenter
putexcel D3=("Climate swaps"), bold hcenter
putexcel E3=("Health Swaps"), bold hcenter
putexcel F3=("Climate + health swaps"), bold hcenter
putexcel B4=("n=1,201"), italic hcenter
putexcel C4=("n=300"), italic hcenter
putexcel D4=("n=301"), italic hcenter
putexcel E4=("n=300"), italic hcenter
putexcel F4=("n=300"), italic hcenter

forvalues i=1/`=_N' {
    local xrow = `i' + 4
    local lbl = label[`i']
    local ov = overall[`i']
    local ct = control[`i']
    local cl = climate[`i']
    local he = health[`i']
    local co = combined[`i']
    if is_heading[`i']==1 {
        putexcel A`xrow'=("`lbl'"), bold
    }
    else {
        putexcel A`xrow'=("`lbl'")
    }
    putexcel B`xrow'=("`ov'") C`xrow'=("`ct'") D`xrow'=("`cl'") E`xrow'=("`he'") F`xrow'=("`co'")
}
local note_row = _N + 6
putexcel A`note_row'=("Note. Missing data ranged from 0.0% to 0.2%."), italic

* 4) Descriptive swaps offered/accepted.
use "$CTData/dataset A_nutri and carbon.dta", clear
keep if inlist(visit_store,2,3) & inlist(treatment_svy,2,3,4)
collapse (mean) ttl_swapoffer prop_swapaccept (sd) sd_swapoffer=ttl_swapoffer sd_prop_swapaccept=prop_swapaccept, by(treatment_svy)
gen arm = cond(treatment_svy==3,"climate swaps",cond(treatment_svy==2,"health swaps","climate + health swaps"))
order arm ttl_swapoffer sd_swapoffer prop_swapaccept sd_prop_swapaccept treatment_svy

* 5) Figure 4 source (acceptability proportions).
use "$CTData/dataset C_Visit3 other outcomes.dta", clear
foreach v in healthlabel_help healthlabel_like healthlabel_approve ///
             climatelabel_help climatelabel_like climatelabel_approve ///
             healthswap_help healthswap_like healthswap_approve ///
             climateswap_help climateswap_like climateswap_approve {
    gen d_`v' = (`v'>=4) if `v'<.
}

tempfile fig4
tempname p4
postfile `p4' str40 variable str20 group double prop using `fig4', replace
foreach v in healthlabel_help healthlabel_like healthlabel_approve ///
             climatelabel_help climatelabel_like climatelabel_approve ///
             healthswap_help healthswap_like healthswap_approve ///
             climateswap_help climateswap_like climateswap_approve {
    quietly summarize d_`v'
    post `p4' ("`v'") ("overall") (r(mean))
    foreach a in 1 3 2 4 {
        quietly summarize d_`v' if treatment_svy==`a'
        local g = cond(`a'==1,"control",cond(`a'==3,"climate",cond(`a'==2,"health","combined")))
        post `p4' ("`v'") ("`g'") (r(mean))
    }
}
postclose `p4'
use `fig4', clear
export delimited using "$ManuscriptFigures/s1_figure_acceptability_of_online_store.csv", replace